### ISSUE TITLE
Pullrequest WR802Nv4 Support

### ISSUE THREAD

**Issue by franzflasch** [drytoastman/scorekeeperrouter#1]
Could you please create a pullrequest for the WR802Nv4 support on the official openwrt repo: https://github.com/openwrt/openwrt

Thanks, regards,
Franz

**Comment by golserma** [comment]
Please upstream the changes

**Comment by golserma** [comment]
I emailed @robimarko maybe we can get this upstream?

**Comment by drytoastman** [comment]
Sorry, I wasn't paying attention to this repository.  @robinmarko is probably the best plan.  I didn't write the patch, I just pulled it from his repo and no longer have a device to test with anyhow.
